language: python
# defaults: the py3.7 environment overrides these
dist: trusty
sudo: false

cache: pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
branches:
  except:
    - /^WIP-.*$/
install:
  - pip install -U pip tox virtualenv codecov
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then
      tox -e flake8 ;
    fi
  - tox -e coverage
after_success:
  - codecov
matrix:
  include:
    - python: 2.7
    - python: 3.3
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
      # we don't actually need sudo, but that kicks us onto GCE, which lets
      # us get xenial
      sudo: true
      dist: xenial
    - python: nightly
  allow_failures:
    - python: 3.3
    - python: nightly
